const $=id=>document.getElementById(id);
const rigChecks=[["skeleton","Skeleton is present and visible in Blender."],["boneNames","Humanoid bone names are mapped for hips, spine, neck, head, arms and legs."],["weights","Mesh weights exist and deform acceptably around shoulders, elbows, hips, knees and ankles."],["orientation","Model scale, orientation and origin are normalised for GLB export."],["clothing","Clothing, hair and textures have source and licence notes."],["handsFeet","Hands and feet remain stable during sample pose tests."]];
const safetyChecks=[["education","Demo is labelled as educational, not medical advice or movement assessment."],["stop","Viewer includes stop, pause, replay, voice-off and fallback controls."],["speed","Animation speed is slow enough for learning."],["form","Motion does not show obviously unsafe joint collapse or extreme range."],["easier","Each exercise includes an easier option."],["review","A human reviewer has marked the clip acceptable for educational demo use."]];
const clips=["squat","lunge","bridge","push","plank","deadbug","balance","cardio","stretch","inchworm","burpee","calf","row"];
const policy={routes:{makehuman:{base:82,name:"MakeHuman official export",note:"Cleanest first route when exported official assets and dependencies are verified."},valid:{base:64,name:"VALID Avatar Library candidate",note:"Promising inclusion/diversity route; package licence and redistribution need review."},anny:{base:68,name:"Anny Body Model research route",note:"Promising open parametric route; tooling and export workflow need validation."},mblab:{base:42,name:"MB-Lab experiment",note:"Technically powerful but GPL/AGPL-style obligations require caution."},mixamo:{base:35,name:"Mixamo workflow asset",note:"Useful workflow tool but not open-source; do not bundle assets without terms review."},manual:{base:50,name:"Manual local model",note:"Depends entirely on source, licence and redistribution evidence."}},licenceScore:{CC0:16,"Apache-2.0":12,MIT:12,GPL:-12,"Research-only":-20,Unknown:-28,"Commercial-restricted":-35},redistributionScore:{approved:14,"local-only":-6,unknown:-20,restricted:-35},attributionScore:{no:4,yes:0,unknown:-8}};
let state={project:{},licence:{},selectedClips:["squat","lunge","push"],rig:{},safety:{}};
function init(){renderChecklists();renderClips();bindEvents();loadFromStorage();analyse()}
function bindEvents(){$("projectForm").addEventListener("submit",e=>{e.preventDefault();analyse();saveToStorage()});$("loadSampleBtn").addEventListener("click",loadSample);$("resetBtn").addEventListener("click",resetProject);$("downloadJsonBtn").addEventListener("click",()=>download("openbody-forge-manifest.json",JSON.stringify(buildManifest(),null,2),"application/json"));$("downloadMarkdownBtn").addEventListener("click",()=>download("openbody-forge-review.md",buildReviewMarkdown(),"text/markdown"));$("copyCommandsBtn").addEventListener("click",copyCommands);document.addEventListener("change",e=>{if(e.target.matches("[data-rig]")||e.target.matches("[data-safety]")||e.target.matches("[data-clip]")){collectCheckboxes();analyse();saveToStorage()}});["projectName","sourceRoute","sourceUrl","declaredLicence","redistribution","attribution","targetExport","blenderPath"].forEach(id=>$(id).addEventListener("input",()=>{analyse();saveToStorage()}))}
function readForm(){return{projectName:$("projectName").value.trim()||"Untitled OpenBody project",sourceRoute:$("sourceRoute").value,sourceUrl:$("sourceUrl").value.trim(),declaredLicence:$("declaredLicence").value,redistribution:$("redistribution").value,attribution:$("attribution").value,targetExport:$("targetExport").value,blenderPath:$("blenderPath").value.trim()||"blender"}}
function renderChecklists(){$("rigChecklist").innerHTML=rigChecks.map(([k,l],i)=>`<label class="check-item"><input type="checkbox" data-rig="${k}" ${i<3?"checked":""}><span>${l}</span></label>`).join("");$("safetyChecklist").innerHTML=safetyChecks.map(([k,l],i)=>`<label class="check-item"><input type="checkbox" data-safety="${k}" ${i<3?"checked":""}><span>${l}</span></label>`).join("")}
function renderClips(){$("clipGrid").innerHTML=clips.map(c=>`<label class="clip-card"><input type="checkbox" data-clip="${c}" ${state.selectedClips.includes(c)?"checked":""}>${c}</label>`).join("")}
function collectCheckboxes(){state.rig={};document.querySelectorAll("[data-rig]").forEach(i=>state.rig[i.dataset.rig]=i.checked);state.safety={};document.querySelectorAll("[data-safety]").forEach(i=>state.safety[i.dataset.safety]=i.checked);state.selectedClips=[...document.querySelectorAll("[data-clip]:checked")].map(i=>i.dataset.clip)}
function loadFromStorage(){const saved=localStorage.getItem("openbody_forge_project");if(!saved)return;try{const data=JSON.parse(saved);if(data.form)Object.entries(data.form).forEach(([k,v])=>{$(k)&&($(k).value=v)});state={...state,...data.state};applyCheckboxState()}catch(e){console.warn(e)}}
function saveToStorage(){localStorage.setItem("openbody_forge_project",JSON.stringify({form:readForm(),state}))}
function applyCheckboxState(){document.querySelectorAll("[data-rig]").forEach(i=>{if(state.rig&&i.dataset.rig in state.rig)i.checked=state.rig[i.dataset.rig]});document.querySelectorAll("[data-safety]").forEach(i=>{if(state.safety&&i.dataset.safety in state.safety)i.checked=state.safety[i.dataset.safety]});document.querySelectorAll("[data-clip]").forEach(i=>i.checked=state.selectedClips?.includes(i.dataset.clip))}
function analyse(){collectCheckboxes();state.project=readForm();state.licence=licenceAssessment(state.project);renderLicence();renderMotion();renderRuntimeMap();renderExport()}
function licenceAssessment(f){const route=policy.routes[f.sourceRoute]||policy.routes.manual;let score=route.base+(policy.licenceScore[f.declaredLicence]||-10)+(policy.redistributionScore[f.redistribution]||-10)+(policy.attributionScore[f.attribution]||0);if(!f.sourceUrl&&f.redistribution!=="approved")score-=8;score=Math.max(0,Math.min(100,Math.round(score)));let verdict="Licence review required",className="caution";if(score>=78&&f.redistribution==="approved"){verdict="Safe candidate for bundled demo";className="good"}else if(score<45||f.redistribution==="restricted"){verdict="Do not bundle yet";className="bad"}const rec=[];if(f.sourceRoute==="mixamo")rec.push("Treat Mixamo as a workflow tool only; do not bundle downloaded assets without Adobe terms review.");if(f.sourceRoute==="mblab")rec.push("Review GPL/AGPL obligations before distributing generated characters.");if(f.declaredLicence==="Unknown")rec.push("Add exact licence text before export.");if(f.redistribution!=="approved")rec.push("Keep asset local until redistribution status is approved.");if(f.attribution!=="no")rec.push("Record attribution text in the asset manifest.");if(!rec.length)rec.push("Proceed to rig validation and motion review before app integration.");return{score,verdict,className,route:route.name,note:route.note,recommendations:rec}}
function renderLicence(){const a=state.licence;$("licenceOutput").innerHTML=`<div class="score-ring">${a.score}</div><div class="verdict ${a.className}">${a.verdict}</div><p><strong>Route:</strong> ${a.route}</p><p>${a.note}</p><ul>${a.recommendations.map(r=>`<li>${r}</li>`).join("")}</ul>`}
function scoreChecklist(o){const v=Object.values(o);return v.length?Math.round(v.filter(Boolean).length/v.length*100):0}
function renderMotion(){const rig=scoreChecklist(state.rig),safe=scoreChecklist(state.safety),n=state.selectedClips.length;$("motionOutput").innerHTML=`<p><strong>${n}</strong> named exercise clip(s) selected.</p><p><strong>Rig readiness:</strong> ${rig}/100</p><p><strong>Safety review:</strong> ${safe}/100</p><p><strong>Retarget status:</strong> ${rig>=70&&n?"Ready for Blender retargeting trial.":"Complete rig checklist and select at least one clip."}</p>`}
function renderRuntimeMap(){const map={avatar:state.project.targetExport||"adult_neutral.glb",fallback:"svg-avatar",runtime:"Three.js GLTFLoader + AnimationMixer",clips:Object.fromEntries(state.selectedClips.map(n=>[n,{clip:n,stages:["setup","move","control","return"]}])),controls:["play","pause","stop","replay","voiceToggle","fallback"]};$("runtimeMap").textContent=JSON.stringify(map,null,2)}
function buildManifest(){const f=readForm();return{schema_version:"0.1.0",project_name:f.projectName,created:new Date().toISOString(),source:{route:f.sourceRoute,source_url_or_note:f.sourceUrl,declared_licence:f.declaredLicence,redistribution_status:f.redistribution,attribution_required:f.attribution},licence_ai:state.licence,target_export:{format:"glb",filename:f.targetExport,browser_runtime:"Three.js GLTFLoader + AnimationMixer",fallback:"SVG educational avatar"},rigging:{score:scoreChecklist(state.rig),checklist:state.rig},motion:{selected_clips:state.selectedClips,target_named_clips:clips},safety_review:{score:scoreChecklist(state.safety),checklist:state.safety,scope:"avatar animation asset review only; not user movement assessment"},blender:{executable:f.blenderPath,scripts:["blender/import_makehuman.py","blender/validate_rig.py","blender/retarget_motion.py","blender/export_glb.py"]},integration:{output_directory:"assets/3d/",manifest_path:"assets/3d/manifest.json"}}}
function blenderCommands(){const f=readForm(),slug=f.projectName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||"openbody-project",b=f.blenderPath||"blender";return[`# 1. Import or create avatar project`,`"${b}" --background --python blender/import_makehuman.py -- --project "${slug}" --source "${f.sourceUrl||"LOCAL_SOURCE"}"`,``,`# 2. Validate humanoid rig`,`"${b}" --background --python blender/validate_rig.py -- --project "${slug}"`,``,`# 3. Retarget selected motion clips`,`"${b}" --background --python blender/retarget_motion.py -- --project "${slug}" --clips "${state.selectedClips.join(",")}"`,``,`# 4. Export app-ready GLB`,`"${b}" --background --python blender/export_glb.py -- --project "${slug}" --output "assets/3d/${f.targetExport}"`].join("\n")}
function renderExport(){$("manifestOutput").textContent=JSON.stringify(buildManifest(),null,2);$("commandsOutput").textContent=blenderCommands()}
function buildReviewMarkdown(){const m=buildManifest();return`# OpenBody Forge AI Review\n\n## Project\n- Name: ${m.project_name}\n- Created: ${m.created}\n- Target export: ${m.target_export.filename}\n- Runtime: ${m.target_export.browser_runtime}\n\n## Licence AI\n- Verdict: ${m.licence_ai.verdict}\n- Score: ${m.licence_ai.score}/100\n- Route: ${m.licence_ai.route}\n- Redistribution: ${m.source.redistribution_status}\n- Licence: ${m.source.declared_licence}\n\n## Rigging\n- Score: ${m.rigging.score}/100\n${Object.entries(m.rigging.checklist).map(([k,v])=>`- ${v?"[x]":"[ ]"} ${k}`).join("\n")}\n\n## Motion clips\n${m.motion.selected_clips.map(c=>`- ${c}`).join("\n")||"- None selected"}\n\n## Safety review\n- Score: ${m.safety_review.score}/100\n- Scope: ${m.safety_review.scope}\n${Object.entries(m.safety_review.checklist).map(([k,v])=>`- ${v?"[x]":"[ ]"} ${k}`).join("\n")}\n\n## Blender commands\n\n\`\`\`bash\n${blenderCommands()}\n\`\`\`\n`}
function download(filename,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
async function copyCommands(){await navigator.clipboard.writeText(blenderCommands());$("copyCommandsBtn").textContent="Copied";setTimeout(()=>$("copyCommandsBtn").textContent="Copy Blender commands",1200)}
function loadSample(){$("projectName").value="MakeHuman Adult Neutral Exercise Avatar v001";$("sourceRoute").value="makehuman";$("sourceUrl").value="MakeHuman official export / verified default assets";$("declaredLicence").value="CC0";$("redistribution").value="approved";$("attribution").value="no";$("targetExport").value="adult_neutral.glb";state.selectedClips=["squat","lunge","bridge","push","plank"];renderClips();document.querySelectorAll("[data-rig]").forEach(i=>i.checked=true);document.querySelectorAll("[data-safety]").forEach((i,n)=>i.checked=n<5);analyse();saveToStorage()}
function resetProject(){localStorage.removeItem("openbody_forge_project");window.location.reload()}
init();
